### ISSUE TITLE
Actual status?

### ISSUE THREAD

**Issue by axlf** [php-sepa-xml/php-sepa-xml#13]
Hey,

what is the actual status of this project?
I read the threads on the digitick account that this should be the new "official" fork. But every reference goes to the digitick repo. 

Wouldn't it be useful to register this repo on its own in packagist?

best wishes,
Alexander

**Comment by monofone** [comment]
Hey,

can you point out what references you mean ?

**Comment by Dazag** [comment]
Well, when you go to add this project to composer is still  "digitick/sepa-xml": "0.10.*", it would be nice to set it up  as:  "php-sepa/sepa-xml": "1.*",

**Comment by monofone** [comment]
Thinking about it, it`s nothing that improves the functionality of this package, it only makes the naming more concise but thats all. But the drawbacks are that all people using this package have to rename this package in the composer.json.

I think this is something for a 2.0 release. That is something which can come together with renaming stuff and using new namespaces and all this funky stuff.

**Comment by Dazag** [comment]
I have to say I lost 1 day an a half until I realise that error. Because targeting 0.1.0 wasn't a valid version for spanish banks.

**Comment by monofone** [comment]
Ok so it is more a problem about documentation ? It is not clear which institutions are supported by this package ?

**Comment by Dazag** [comment]
Yes, I think It would be better to point out that you need latest version to have Spanish banks supports. That would be great

**Comment by BenjaminPaap** [comment]
@Dazag can you provide updated documentation? It would be great to have the text from a person that had these problems already.

**Comment by Dazag** [comment]
@BenjaminPaap could you please tell me how can I help. Since then, they have added "dev-master" to the documentation, so my problem doesn't happen again. Maybe you mean something else?

**Comment by BenjaminPaap** [comment]
@axlf Just to give you a quick update. I wrote numerous mails to all the guys from @digitick. I asked if they can update the readme to make it clear that their repository is no longer maintained.

**Comment by monofone** [comment]
We released this repository from the parent this one was originally forked from as this is now the main repository.

@Dazag can you please name the spanish bank you use this lib with. We like to start to collect all supported banks and the used pain format if available.

**Comment by Dazag** [comment]
I've used it with a bank called [Cajamar](https://www.cajamar.es/en/comun/), using: pain.008.001.02

**Comment by monofone** [comment]
Started Wiki pages to collect information about supported institutions and software

**Comment by BorislavSabev** [comment]
Hey, everybody. Just a note on institution/country/region support and the ISO20022 standard. Some remarks from my experience.
Although the ISO20022 standard is widely accepted and implemented, at least in the SEPA region, the different countries and institutions all support different versions of the standard. As a result version support information is a mess.

- You should always verify the exact standard version with the bank(s) you are going to be issuing the files to. 
- After generating your files you can check their structure against the relevant XSD file from the [ISO20022 website](https://www.iso20022.org/full_catalogue.page). So just get the exact standard version supported by the bank(s) you'll be using i.e. [pain.008.001.06 and download the XSD](https://www.iso20022.org/documents/messages/pain/schemas/pain.008.001.06.zip) from the ISO20022 web site. All historical versions are available [in the message archive](https://www.iso20022.org/message_archive.page) as schema files there.

Then via DomDocument:
(I am just writing this here so beware :) )
```
$domDoc = new DomDocument();
$domDoc->loadXML($pathToGeneratedXml);
//The following will return TRUE if the generated file  validates against the XSD schema
$domDoc->schemaValidate($pathToXsdSchemaFile);
...
```
This can be used as a first step before delivering the file to your bank. If  it validates then you can send the files for a test to the bank.

- All banks have their own business rules' systems so your file may nevertheless be rejected from them after passing the XSD check. You should always make several tests on this with the institution(s).
- Almost all institutions also have legacy systems that are somehow incorporated in the process. Or at the least they are running their (legacy) local business rules validation
- There are also region/country specific rules depending on the payment types

And some resources:
- There is the [XMLdation wiki](https://wiki.xmldation.com/General_Information/ISO_20022) which has a lot of useful information for the different countries and business rules. They just outline general information because their products are centered on such systems but still there are useful pieces there.
- I've been compiling an open source wiki on ISO20022 my self for some time now, but my data is not fully organized yet. I just published a [public repo](https://github.com/BorislavSabev/ISO20022_php_wiki) and I will start adding information and structure to it from what I have compiled for the last 3,5 years.

Hope this helped.
