### ISSUE TITLE
CreDtTm defaults to local datetime value but default format expects "Zulu" timezone

### ISSUE THREAD

**Issue by sunlix** [php-sepa-xml/php-sepa-xml#164]
Hey,

I just noticed that the CreDtTm defaults to the current datetime in my local timezone but the default format expects a datetime value corresponding to  the "Zulu" timezone (UTC == +0:00).
So I think it should be add `$this->creationDateTime->setTimezone(new \DateTimeZone('UTC'));` to the `GroupHeader` constructor.

But I think due to the fact, that the datetime format can be altered the datetime handling have to reflect that so that the datetime value always corresponding to the timezone given in the datetime format.

What dou you think?

**Comment by BorislavSabev** [comment]
Yes, it does default to the current timezone as this is expected behavior. 
The standard does not imply that one must use the "Zulu" timezone at all. The standard uses ISO 8601 which carries the offset from UTC in it's format. 
All dates are already formatted according to those rules. 
Thus you can affect which timezone is used by adjusting your application or environment pre or at runtime.

In practice this is linked to: https://github.com/php-sepa-xml/php-sepa-xml/issues/159 and #160
