### ISSUE TITLE
Make sure <ReqdColltnDt> is a TARGET2 day

### ISSUE THREAD

**Issue by osopolar** [php-sepa-xml/php-sepa-xml#58]
https://en.wikipedia.org/wiki/TARGET2#Holidays

> Holidays
>
> The TARGET2 system is closed on Saturdays and Sundays and on the following public holidays in all participating countries: 1 January, Good Friday and Easter Monday (according to the calendar used by Western Christianity), 1 May, 25 December and 26 December.

So it should not be possible to choose these days for <ReqdColltnDt> as some banks may reject transfers. Is that something which should be validated/fixed by php-sepa-xml or should that be implemented outside (done before setting dueDate)?

**Comment by osopolar** [comment]
Maybe dateIsTargetDay() from https://github.com/AbcAeffchen/SepaUtilities/blob/master/src/SepaUtilities.php may help?

**Comment by monofone** [comment]
In my opinion this is something the application is responsible for. The php-sepa-xml library is only for creating the XML correctly. 

I also prefer to remove the conversion from float to int as this is something the library should not know about.

Even the calculation of the total is something you can discuss.

By the way how do you transfer these files to the banking Institute ?

Regards Sören

**Comment by osopolar** [comment]
I thought so too, but as it seems to be something easy to overlook and as there is already some logic to calculate the dueDate (as it is not a required field) it could mislead developers. I first thought that php-sepa-xml ensures that the dueDate is checked against the terms corresponding to seqType, but that was not true. So maybe there should be some additional Information in the documentation of dueDate.

The SEPA-XML gets created by a custom Drupal module. As we currently can't upload the sepa-xml files to the web-app we will use Starmoney 8 Business for that. So it's not (yet) an automated process.

**Comment by monofone** [comment]
It's something the factory could know about IR a second package utilising this one and create a framework around to abstract the usage a little bit more and try to make it simpler. 

In the other side, you can't use this without at least a little knowledge about SEPA so you will at least know which dates you can use. As this also depends in the country and even the state inside a country can have different holidays each.

I think this needs more discussion about what Problem to solve with this library.

**Comment by BorislavSabev** [comment]
@monofone I can't agree more - that is purely business logic and it lies solely in the business domain.
However I would like to add an XSD validation step after the file is written to disk. This could also be regarded as business logic as it is one method call over a DomDocument object. I do do this to all SEPA files we generate.

I just wanted to add about the SEPA file transfers to institutions. I use [Exabanque](http://www.exabanque.com/en) by [Exalog](http://www.exalog.com/en).
Five years ago we were forced to use a 3rd party system to transfer the files to our banks since the EBICS protocol had no Linux implementation. I did think that this is the only feasible use but in fact any such system will run pre-validations over your files and most systems will go much further than just verifying file syntax. So in my opinion these specialized systems are indeed useful even if you only push your files through them and get return messages back.
